language: java
jdk:
  - oraclejdk8
addons:
  firefox: "latest"
before_script:
  - "export DISPLAY=:99.0"
  - "export TEMPDIR=~/tmp"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "target/updater.jar"
  skip_cleanup: true
  on:
    tags: true