language: java
jdk:
  - oraclejdk8
addons:
  firefox: "latest"
before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 +extension RANDR"
  - sleep 3 # give xvfb some time to start
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "target/updater.jar"
  skip_cleanup: true
  on:
    tags: true