language: java
jdk:
  - oraclejdk8
addons:
  firefox: "latest"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "wget http://selenium-release.storage.googleapis.com/3.0-beta3/selenium-server-standalone-3.0.0-beta3.jar"
  - "java -jar selenium-server-standalone-3.0.0-beta3.jar > /dev/null &"
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "target/updater.jar"
  skip_cleanup: true
  on:
    tags: true