<?php

/**
 * GroupMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    IBWUpdater
 * @subpackage Datamodel
 * @author     René Adler <rene.adler@tu-ilmenau.de>
 * @version    $Revision$
 */
class GroupMember extends BaseGroupMember
{

}