<?php

/**
 * GroupMemberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupMemberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupMemberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupMember');
    }
}