<?php

/**
 * JSFunctionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JSFunctionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JSFunctionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JSFunction');
    }
}